### ISSUE TITLE
fatal runtime error: Rust cannot catch foreign exceptions when syncing target=#6745651

### ISSUE THREAD

**Issue by stringa** [paritytech/polkadot#3817]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
```
host: https://app.cloud.dynacentri.net/
version: 0.9.9-1 was version at the time of testing.
Distro: Linux / Ubuntu 16.04
Dockerfile here: https://github.com/stringa/jelastic_polkadot
Dockerimage here: https://hub.docker.com/repository/docker/stringa/jelastic-polkadot-validator
```

- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
```
2021-09-09 00:33:48 🔍 Discovered new external address for our node: /ip4/10.2.112.235/tcp/30333/p2p/12D3KooWAtZjqMFqXemUDb9F2k2siTb8H7soJtWSTGMSfdLRXdPH
2021-09-09 00:33:48 ⚙️ Syncing 0.0 bps, target=#6745651 (43 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 146.6kiB/s ⬆ 58.4kiB/s
fatal runtime error: Rust cannot catch foreign exceptions
Aborted
```

- Describe the role your node plays, e.g. validator, full node or light client.
```
    Testing out hosting a validator in the cloud. Current Host can not use Ubuntu 18 as recommended in tutorial
```
- Any command-line options were passed?
    --name='hashinFrog-polkadot-1' --validator

**Comment by stringa** [comment]
Got another issue bringing it back up. Testing out v0.9.8 on ubuntu16 with the same data from the previous failed sync

```
root@node2933-hashyfrog-polkadot-1:~# RUST_BACKTRACE=full polkadot --validator
2021-09-09 02:52:12 Parity Polkadot    
2021-09-09 02:52:12 ✌  version 0.9.8-3a10ee6-x86_64-linux-gnu    
2021-09-09 02:52:12 ❤  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-09-09 02:52:12  Chain specification: Polkadot    
2021-09-09 02:52:12  Node name: melodic-nest-7761    
2021-09-09 02:52:12  Role: AUTHORITY    
2021-09-09 02:52:12  Database: RocksDb at /root/.local/share/polkadot/chains/polkadot/db    
2021-09-09 02:52:12 ⛓  Native runtime: polkadot-9080 (parity-polkadot-0.tx7.au0)    
2021-09-09 02:52:14  Local node identity is: 12D3KooWAtZjqMFqXemUDb9F2k2siTb8H7soJtWSTGMSfdLRXdPH    
Error: 
   0: Future version (expected 0, found 1)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮                               
   3: polkadot::main::hdcb3b3554aa8eddc
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_begin_short_backtrace::hb8a49ceb0388d3ba
      at <unknown source file>:<unknown line>
   5: std::rt::lang_start::{{closure}}::h43c8c69b82927414
      at <unknown source file>:<unknown line>
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259
   7: std::panicking::try::do_call::hc5fcacb7a85fc7b1
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401
   8: std::panicking::try::hb5d9603af3abbe3a
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365
   9: std::panic::catch_unwind::h98fe6ac3925e64b4
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434
  10: std::rt::lang_start_internal::h22ac7383c516f93e
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34
  11: main<unknown>
      at <unknown source file>:<unknown line>
  12: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  13: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
root@node2933-hashyfrog-polkadot-1:~# COLORBT_SHOW_HIDDEN=1 RUST_BACKTRACE=full polkadot --validator
2021-09-09 02:52:55 Parity Polkadot    
2021-09-09 02:52:55 ✌  version 0.9.8-3a10ee6-x86_64-linux-gnu    
2021-09-09 02:52:55 ❤  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-09-09 02:52:55  Chain specification: Polkadot    
2021-09-09 02:52:55  Node name: slimy-boy-2425    
2021-09-09 02:52:55  Role: AUTHORITY    
2021-09-09 02:52:55  Database: RocksDb at /root/.local/share/polkadot/chains/polkadot/db    
2021-09-09 02:52:55 ⛓  Native runtime: polkadot-9080 (parity-polkadot-0.tx7.au0)    
2021-09-09 02:52:57  Local node identity is: 12D3KooWAtZjqMFqXemUDb9F2k2siTb8H7soJtWSTGMSfdLRXdPH    
Error: 
   0: Future version (expected 0, found 1)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::hb1baeff3cbea5365
      at <unknown source file>:<unknown line>
   2: eyre::capture_handler::h2dea9c80b4ddcacf
      at <unknown source file>:<unknown line>
   3: polkadot::main::hdcb3b3554aa8eddc
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_begin_short_backtrace::hb8a49ceb0388d3ba
      at <unknown source file>:<unknown line>
   5: std::rt::lang_start::{{closure}}::h43c8c69b82927414
      at <unknown source file>:<unknown line>
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259
   7: std::panicking::try::do_call::hc5fcacb7a85fc7b1
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401
   8: std::panicking::try::hb5d9603af3abbe3a
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365
   9: std::panic::catch_unwind::h98fe6ac3925e64b4
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434
  10: std::rt::lang_start_internal::h22ac7383c516f93e
      at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34
  11: main<unknown>
      at <unknown source file>:<unknown line>
  12: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  13: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

**Comment by bkchr** [comment]
The second error is related to the parachain db. Removing should fix it.

**Comment by stringa** [comment]
I thought I was just trying to fresh sync the parachain db. Removing it seems to hit the error again. 

I updated to the suggested Ubuntu18 and I am getting a similar error as the original error on a different block. I can't seem to run the exact docker image supplied by Parity, but I am getting it really close to what they have. 

I will be posting another error soon for a different block.using my newest docker setup

**Comment by stringa** [comment]
Using the latest v0.9.10 code + updateding to Ubuntu18, I'm still unable to sync the blockchain.

```
host: https://app.cloud.dynacentri.net/
version: 0.9.9-1 was version at the time of testing.
Distro: Linux / Ubuntu 16.04
Dockerfile here: https://github.com/stringa/jelastic_polkadot
Dockerimage here: https://hub.docker.com/repository/docker/stringa/jelastic-polkadot-validator tagged v0.9.10-ubuntu18
```

New error off syncing with the latest client.
```
2021-09-09 12:56:53 ⚙️ Syncing 0.0 bps, target=#6753078 (50 peers), best: #3899547 (0x9548…8aca), finalized #3899392 (0x2395…cf6f), ⬇ 148.4kiB/s ⬆ 57.6kiB/s
2021-09-09 12:56:57 🔍 Discovered new external address for our node: /ip4/192.168.78.64/tcp/30333/p2p/12D3KooW9pXuFP2aTSZsJEnfjQpY43VNoA6Gn7NRPxhYY7Z3LwWk
2021-09-09 12:56:57 🔍 Discovered new external address for our node: /ip4/10.2.96.13/tcp/30333/p2p/12D3KooW9pXuFP2aTSZsJEnfjQpY43VNoA6Gn7NRPxhYY7Z3LwWk
fatal runtime error: Rust cannot catch foreign exceptions
Aborted
```

I've set RUST_BACKTRACE=1 as an env variable on the whole environment, so that should be set for any subprocess and I'm still seeing the same error. 

Is there a good version to use that would allow me to sync the blockchain from initial install? Am I the only one having trouble syncing the full chain so I can get my validator up and working?

Is there something wrong with my Dockerfile that is forcing this to cause an exception where no others are getting execption?

I've done my best to follow the tutorial and look at the existing dockerfile to create my setup. It's pretty simple and straightforward. Next step would be for me to figure out where in code this is happening.

**Comment by stringa** [comment]
@bkchr  I see that 12 hours of testing is required for new releases, but that is not on the parachain from what I can tell, and it''s not clear it's using a fresh sync versus an existing DB.

**Comment by stringa** [comment]
This has been a roadblocker for me. It would be great to know if should be using a different chain, but I literally have this thing processing about 2/3rd's of the blockchain and then craps out

**Comment by bkchr** [comment]
@stringa could you please try running master. Please make sure to run with `--execution wasm`

**Comment by stringa** [comment]
@bkchr i added the cli options to the existing container, and it seems to be moving forward now after a restart. gonna keep my eye on it. if I see more breakages, and I see an exception, I will post it

**Comment by stringa** [comment]
Stuck again:

2021-09-13 23:53:51 ⚙️ Syncing 0.0 bps, target=#6817185 (12 peers), best: #4876134 (0x89b9…466e), finalized #4875785 (0x095a…c7a5), ⬇ 434.0kiB/s ⬆ 156.2kiB/s
2021-09-13 23:53:51 ❌ Error while dialing /dns/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Timeout }

**Comment by stringa** [comment]
2021-09-13 23:55:31 ⚙️ Syncing 0.0 bps, target=#6817202 (41 peers), best: #4876134 (0x89b9…466e), finalized #4875785 (0x095a…c7a5), ⬇ 198.7kiB/s ⬆ 80.7kiB/s
2021-09-13 23:55:32 poll_actions: Background import task is no longer alive
2021-09-13 23:55:32 poll_actions: Background import task is no longer alive
2021-09-13 23:55:32 poll_actions: Background import task is no longer alive
fatal runtime error: Rust cannot catch foreign exceptions
Aborted

**Comment by bkchr** [comment]
@stringa please run with `-lsync=trace` and upload the logs somewhere and link them here. Be aware that this can generate a lot of output.

**Comment by stringa** [comment]
@bkchr  Here is a link to my run.log: https://www.dropbox.com/s/euruqvijf4z1gao/run.log?dl=0
