### ISSUE TITLE
Peer discovery not working in 0.9.43

### ISSUE THREAD

**Issue by tmpolaczyk** [paritytech/polkadot#7428]
Peer discovery seems to be broken in the 0.9.43 release. This affects polkadot as well as template parachains based on cumulus, etc. It is impossible to start a local network unless one of the nodes is added as a boot node.

Steps to reproduce: launch 2 nodes in 2 separate terminals and verify how the peer count stays at 0. 

```
./polkadot build-spec --chain rococo-local --disable-default-bootnode --raw > rococo-local-cfde.json
./polkadot --chain rococo-local-cfde.json --alice --tmp
./polkadot --chain rococo-local-cfde.json --bob --tmp
```

Sample logs:
```
2023-06-26 16:31:51 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
```

This last worked in 0.9.42, can be easily reproduced by downloading the release binary and running the above commands.

Sample logs (0.9.42):

```
2023-06-26 16:37:16 💤 Idle (1 peers), best: #1 (0x4715…e3ed), finalized #0 (0xcbcd…e878), ⬇ 1.5kiB/s ⬆ 1.3kiB/s    
```

**Comment by altonen** [comment]
It looks like 0.9.43 is able to discover 0.9.42 but not vice versa so there could be something wrong in the mDNS advertisement 0.9.43 sends

**Comment by altonen** [comment]
Fixed in https://github.com/paritytech/substrate/pull/14478

**Comment by altonen** [comment]
How is https://github.com/paritytech/polkadot/commit/ba42b9ce51d25bdaf52d2c61e0763a6e3da50d25 related to peer discovery? Please open a new issue if believe there is a problem with 0.9.43

**Comment by ntn-x2** [comment]
I am just saying that the HEAD of the 0.9.43 branch is the commit I linked above, which is dated 08/06. The fix was merged into Substrate late June, so this means that 0.9.43 branch is still broken (that's how I ended up on here). So I think this issue should actually be re-opened, since it has not been fixed, really.

**Comment by altonen** [comment]
I see. I don't believe our backporting policies apply to any kind of bug fix but somebody can correct me on that. I'm fine with backporting this to 0.9.43 though if it's something we'd want to do

cc @bkchr @coderobe
